global:
  scrape_interval: 4s          # Sab targets ko har 4 second mein scrape karega
  evaluation_interval: 15s     # Rules ya alerts ko 15 second mein check karega

scrape_configs:
  - job_name: "fastapi-service"
    scrape_interval: 4s        # Is job ke liye 4 second interval override karta hai global ko
    static_configs:
      - targets: ["192.168.137.6:8080"]
