global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-service'
    static_configs:
      - targets: ['172.24.192.1:8080']

  - job_name: 'loki'
    static_configs:
      - targets: ['172.24.192.1:3100']
