global:
  scrape_interval: 4s          
  evaluation_interval: 15s     

scrape_configs:
  - job_name: "fastapi-service"
    scrape_interval: 4s       
    static_configs:
      - targets: ["172.24.192.1:8080"]
