version: '3.8'

services:
  redis-service:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  src-service:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: src-image
    container_name: src-container
    ports:
      - "8080:8080"
    depends_on:
      - redis-service
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
    networks:
      - app-network

  nginx-service:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-image
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - src-service
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
