version: '3.8'

services:
  redis-service:
    image: redis:alpine  # no need to build unless you're customizing
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  src-service:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: src-image
    container_name: src-container
    ports:
      - "8080:8080"
    depends_on:
      - redis-service
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379

volumes:
  redis-data:
